version: "3.8"

services:
    web:
        container_name: chuck-norris
        restart: always
        build: .
        ports:
            - "8021:8021"
        links:
            - mongo
    mongo:
        container_name: mongo-chuck-norris
        image: mongo
        ports:
            - "27017:27017"

    